name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Build with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    
    - name: Test (NPM)
      run: npm test
     
  build-composer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Sniff PHP
      run: composer run-script phpcs
      
    - name: Start MySQL
      run: sudo /etc/init.d/mysql start
      
    - name: Install WordPress test environment
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1

    - name: Test (Composer)
      run: composer run-script phpunit
